version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: artivio_postgres
    environment:
      POSTGRES_DB: artivio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"